"use client";

import {useEffect,useRef,useState} from "react";
import {ArrowLeft,CheckCircle2,Eraser,Printer,Save,Signature,Wrench} from "lucide-react";
import "../previsite/previsite.css";
import "./maintenance.css";

const controls={
  "Sécurité et état général":["Absence de bruit ou vibration anormale","Fixations et supports en bon état","Capotages et protections présents","Dégagement autour des unités suffisant","Absence de corrosion importante","Étiquettes et références lisibles","État des liaisons et isolants","Absence de fuite d’eau visible"],
  "Contrôles électriques":["Serrage des connexions électriques","État des câbles et borniers","Protection différentielle contrôlée","Disjoncteur adapté à l’installation","Mise à la terre vérifiée","Intensité absorbée conforme","Tension d’alimentation conforme","Absence de traces d’échauffement"],
  "Unité extérieure":["Nettoyage de l’échangeur extérieur","État des ailettes","Ventilateur et hélice contrôlés","Évacuation des condensats contrôlée","Supports antivibratiles contrôlés","Bac à condensats propre","État du compresseur","Fonctionnement du dégivrage"],
  "Unité intérieure / climatisation":["Nettoyage et désinfection des filtres","Nettoyage de l’échangeur intérieur","Nettoyage de la turbine","Nettoyage du bac à condensats","Débouchage de l’évacuation","Contrôle de la pompe de relevage","Contrôle des volets et moteurs","Contrôle du débit d’air","Télécommande et affichage testés","Désinfection de l’unité intérieure"],
  "Circuit frigorifique":["Recherche visuelle de fuite","Contrôle des raccords flare","Contrôle des traces d’huile","État de l’isolation frigorifique","Pressions de fonctionnement relevées","Températures aspiration/refoulement relevées","Surchauffe contrôlée","Sous-refroidissement contrôlé","Charge de fluide cohérente","Détecteur de fuite utilisé si nécessaire"],
  "Hydraulique pompe à chaleur":["Pression du circuit chauffage","Purge de l’installation","Vase d’expansion contrôlé","Filtre ou pot à boue nettoyé","Circulateur contrôlé","Soupape de sécurité contrôlée","Débit d’eau vérifié","Températures départ/retour relevées","Absence de fuite hydraulique","Qualité de l’eau contrôlée","Appoint d’eau effectué si nécessaire"],
  "Régulation et essais":["Thermostat et consignes contrôlés","Programmation horaire vérifiée","Sondes de température contrôlées","Mode chauffage testé","Mode climatisation testé","Production ECS testée","Basculement appoint électrique testé","Communication Wi-Fi testée","Codes défauts consultés","Historique des défauts relevé","Essai complet après entretien"],
  "Obligations et environnement":["État d’étanchéité évalué","Quantité et type de fluide identifiés","Registre équipement renseigné si applicable","Déchets et consommables récupérés","Zone de travail nettoyée","Client informé des anomalies","Conseils d’utilisation donnés au client"]
};

function Field({label,name,type="text",wide=false,children}){return <label className={wide?"wide":""}><span>{label}</span>{children||<input name={name} type={type}/>}</label>;}
function CheckRow({section,index,label}){return <div className="control-row"><span>{label}</span><label><input type="radio" name={`control_${section}_${index}`} value="Conforme"/>Conforme</label><label><input type="radio" name={`control_${section}_${index}`} value="À corriger"/>À corriger</label><label><input type="radio" name={`control_${section}_${index}`} value="Non applicable"/>N/A</label><input name={`note_${section}_${index}`} placeholder="Observation"/></div>;}
function SignaturePad({storageKey,title}) {
  const canvas=useRef(null),drawing=useRef(false);
  useEffect(()=>{const el=canvas.current,ratio=devicePixelRatio||1,rect=el.getBoundingClientRect();el.width=rect.width*ratio;el.height=rect.height*ratio;const ctx=el.getContext("2d");ctx.scale(ratio,ratio);ctx.lineWidth=2;ctx.lineCap="round";ctx.strokeStyle="#27427f";const saved=localStorage.getItem(storageKey);if(saved){const image=new Image();image.onload=()=>ctx.drawImage(image,0,0,rect.width,rect.height);image.src=saved;}},[storageKey]);
  const point=e=>{const r=canvas.current.getBoundingClientRect(),s=e.touches?.[0]||e;return{x:s.clientX-r.left,y:s.clientY-r.top};};
  const start=e=>{e.preventDefault();drawing.current=true;const p=point(e),ctx=canvas.current.getContext("2d");ctx.beginPath();ctx.moveTo(p.x,p.y);};
  const move=e=>{if(!drawing.current)return;e.preventDefault();const p=point(e),ctx=canvas.current.getContext("2d");ctx.lineTo(p.x,p.y);ctx.stroke();};
  const stop=()=>{if(drawing.current)localStorage.setItem(storageKey,canvas.current.toDataURL());drawing.current=false;};
  const clear=()=>{canvas.current.getContext("2d").clearRect(0,0,canvas.current.width,canvas.current.height);localStorage.removeItem(storageKey);};
  return <div className="signature-pad"><div><Signature size={17}/><b>{title}</b><button type="button" onClick={clear}><Eraser size={14}/>Effacer</button></div><canvas ref={canvas} onMouseDown={start} onMouseMove={move} onMouseUp={stop} onMouseLeave={stop} onTouchStart={start} onTouchMove={move} onTouchEnd={stop}/><small>Signer avec le doigt ou le stylet</small></div>;
}

export default function MaintenanceForm(){
  const [saved,setSaved]=useState(false);const [recordKey,setRecordKey]=useState("new");
  useEffect(()=>{const query=new URLSearchParams(location.search),key=query.get("contract")||query.get("id")||"new";setRecordKey(key);let data={};try{data=JSON.parse(localStorage.getItem(`mkl-maintenance-report-${key}`)||"{}");}catch{}for(const [name,value] of Object.entries(data)){document.querySelectorAll(`[name="${name}"]`).forEach(field=>{if(field.type==="radio"||field.type==="checkbox")field.checked=field.value===value||value==="on";else field.value=value??"";});}for(const [name,value] of query){const field=document.querySelector(`[name="${name}"]`);if(field)field.value=value;}},[]);
  function save(event){const form=event.currentTarget.closest(".maintenance-app").querySelector("form"),data=Object.fromEntries(new FormData(form));localStorage.setItem(`mkl-maintenance-report-${recordKey}`,JSON.stringify(data));setSaved(true);setTimeout(()=>setSaved(false),2200);}
  return <main className="previsit-app maintenance-app"><header className="form-toolbar"><button onClick={()=>location.href="/"}><ArrowLeft/>Retour CRM</button><div><Wrench size={18}/><span><b>Rapport de maintenance</b><small>Climatisation & pompe à chaleur</small></span></div><div><button onClick={save}><Save/>Enregistrer</button><button className="print" onClick={()=>window.print()}><Printer/>Imprimer / PDF</button></div></header>{saved&&<div className="save-toast"><CheckCircle2/>Rapport enregistré sur cet appareil</div>}
    <form>
      <section className="paper">
        <div className="document-head"><img src="/mkl-energies.png" alt="MKL Énergies"/><div><span>CONTRAT D’ENTRETIEN</span><h1>Rapport de maintenance</h1><p>Climatisation • Pompe à chaleur • Eau chaude sanitaire</p></div></div>
        <h2>Identification du client et de l’installation</h2>
        <div className="field-grid"><Field label="N° de contrat" name="contract"/><Field label="Date d’intervention" name="date" type="date"/><Field label="Heure d’arrivée" name="startTime" type="time"/><Field label="Heure de départ" name="endTime" type="time"/><Field label="Client" name="client" wide/><Field label="Technicien" name="technician"/><Field label="Téléphone" name="phone"/><Field label="Adresse de l’installation" name="address" wide/><Field label="Email" name="email" type="email"/><Field label="Type d’équipement" name="equipmentType"><select name="equipmentType"><option>Pompe à chaleur air/eau</option><option>Climatisation monosplit</option><option>Climatisation multisplit</option><option>Pompe à chaleur air/air</option><option>Ballon thermodynamique</option><option>Système hybride</option><option>Autre</option></select></Field><Field label="Marque" name="brand"/><Field label="Modèle" name="model"/><Field label="N° de série" name="serial"/><Field label="Date de mise en service" name="commissioningDate" type="date"/><Field label="Fluide frigorigène" name="refrigerant"/><Field label="Charge indiquée (kg)" name="refrigerantCharge" type="number"/></div>
        <h2>État à l’arrivée</h2>
        <div className="field-grid"><Field label="Demande ou plainte du client" name="customerRequest" wide><textarea name="customerRequest" rows="4"/></Field><Field label="Code défaut affiché" name="faultCode"/><Field label="État de fonctionnement" name="initialState"><select name="initialState"><option>Fonctionnement normal</option><option>Fonctionnement dégradé</option><option>À l’arrêt</option><option>Panne intermittente</option></select></Field></div>
        <h2>Mesures de fonctionnement</h2>
        <div className="measure-grid"><Field label="Température extérieure (°C)" name="outsideTemp" type="number"/><Field label="Température intérieure (°C)" name="insideTemp" type="number"/><Field label="Soufflage (°C)" name="supplyAirTemp" type="number"/><Field label="Reprise (°C)" name="returnAirTemp" type="number"/><Field label="Départ chauffage (°C)" name="flowTemp" type="number"/><Field label="Retour chauffage (°C)" name="returnWaterTemp" type="number"/><Field label="Pression eau (bar)" name="waterPressure" type="number"/><Field label="Basse pression (bar)" name="lowPressure" type="number"/><Field label="Haute pression (bar)" name="highPressure" type="number"/><Field label="Intensité compresseur (A)" name="compressorCurrent" type="number"/><Field label="Tension (V)" name="voltage" type="number"/><Field label="Débit / delta T" name="flowDelta"/></div>
      </section>
      <section className="paper maintenance-controls"><div className="document-head compact"><img src="/mkl-energies.png" alt="MKL Énergies"/><div><span>POINTS DE CONTRÔLE</span><h1>Maintenance préventive</h1><p>Cocher chaque point et préciser toute anomalie.</p></div></div>{Object.entries(controls).map(([section,items])=><section className="control-section" key={section}><h2>{section}</h2><div className="control-head"><span>Point contrôlé</span><span>Conforme</span><span>À corriger</span><span>N/A</span><span>Observation</span></div>{items.map((item,index)=><CheckRow section={section} index={index} label={item} key={item}/>)}</section>)}</section>
      <section className="paper"><div className="document-head compact"><img src="/mkl-energies.png" alt="MKL Énergies"/><div><span>CONCLUSION</span><h1>Compte rendu d’intervention</h1><p>Résultat, recommandations et validation du client.</p></div></div>
        <h2>Travaux réalisés et consommables</h2><div className="field-grid"><Field label="Opérations effectuées" name="workDone" wide><textarea name="workDone" rows="6"/></Field><Field label="Pièces / consommables utilisés" name="partsUsed" wide><textarea name="partsUsed" rows="6"/></Field></div>
        <h2>Anomalies et recommandations</h2><div className="field-grid"><Field label="Anomalies constatées" name="anomalies" wide><textarea name="anomalies" rows="5"/></Field><Field label="Travaux ou devis recommandés" name="recommendations" wide><textarea name="recommendations" rows="5"/></Field></div>
        <div className="field-grid"><Field label="État final de l’installation" name="finalState"><select name="finalState"><option>Fonctionnelle et conforme</option><option>Fonctionnelle avec réserves</option><option>Arrêt conseillé</option><option>Mise hors service</option><option>Devis complémentaire nécessaire</option></select></Field><Field label="Prochaine maintenance conseillée" name="nextMaintenance" type="date"/><Field label="Temps passé (heures)" name="duration" type="number"/><Field label="Intervention facturable" name="billable"><select name="billable"><option>Incluse au contrat</option><option>Facturable</option><option>Sous garantie</option></select></Field></div>
        <label className="consent"><input type="checkbox" name="customerValidation" required/>Le client reconnaît que l’intervention a été réalisée, que les constats lui ont été présentés et qu’une copie du rapport peut lui être remise.</label>
        <div className="signature-grid"><SignaturePad storageKey={`mkl-maintenance-${recordKey}-technician`} title="Signature du technicien"/><SignaturePad storageKey={`mkl-maintenance-${recordKey}-client`} title="Signature du client"/></div>
        <p className="legal">Rapport électronique MKL Énergies. Les mesures sont relevées dans les conditions présentes le jour de l’intervention. Toute manipulation de fluide frigorigène doit être réalisée par un opérateur habilité conformément à la réglementation applicable.</p>
      </section>
    </form>
  </main>;
}
